pub mod console_commands;
mod build_city_console_command;
mod list_builds_command;
mod show_board_command;
mod list_moves_command;
mod expand_population_command;
mod start_command;
mod player_end_building_command;
mod stupid_ai_command;
mod make_a_move_command;